version: '3.0'

services: 
  angular:
    hostname: localhost
    build: alke-organic-food
    ports: 
      - 4200:80
  express: 
    build: express-server
    ports: 
      - "3000:3000"
    links: 
      - database
  
  database:
    image: mongo
    ports: 
      - "27017:27017"
 
 